kind: Deployment
apiVersion: apps/v1
metadata:
  name: evmos-proposal-atomfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evmos-proposal-atomfeed
  template:
    metadata:
      labels:
        app: evmos-proposal-atomfeed
    spec:
      containers:
      - args:
        image: derorisan/evmos-proposal-atomfeed
        imagePullPolicy: Always
        name: evmos-proposal-atomfeed
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: PROPS_ENDPOINT
          value: https://rest.evmos.lava.build/cosmos/gov/v1/proposals?proposal_status=PROPOSAL_STATUS_UNSPECIFIED&pagination.limit=10&pagination.reverse=true
        - name: LINK_BASE_URL
          value: https://www.mintscan.io/evmos/proposals/
---
kind: Service
apiVersion: v1
metadata:
  name: evmos-proposal-atomfeed
spec:
  ports:
  - name: "http-port"
    protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: evmos-proposal-atomfeed
---
# # ingress
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: lb
#   namespace: ip-deroris-net-prod
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: evmos-proposal-atomfeed.deroris.net
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: evmos-proposal-atomfeed
#                 port:
#                   number: 80